---
- name: Check for installed elasticsearch plugins - azure-repository
  command: "/usr/share/elasticsearch/bin/elasticsearch-plugin list"
  register: elasticsearch_installed_plugins
  changed_when: false

- name: install Azure Repository Plugin
  become: yes
  command: "/usr/share/elasticsearch/bin/elasticsearch-plugin install --batch {{ elasticsearch_backup_plugin_pkg_url }}"
  when: elasticsearch_installed_plugins.stdout.find('repository-azure') == -1

- name: Check the current keystore configuration
  command: "/usr/share/elasticsearch/bin/elasticsearch-keystore list"
  changed_when: false
  register: keystore

- name: Add default Azure account
  shell: "echo {{ elk_backup_storage_azure_account }} | /usr/share/elasticsearch/bin/elasticsearch-keystore add -xf azure.client.default.account"
  when: keystore.stdout.find("azure.client.default.account") == -1

- name: Add account key
  shell: "echo {{ elk_backup_storage_azure_key }} | /usr/share/elasticsearch/bin/elasticsearch-keystore add -xf azure.client.default.key"
  when: keystore.stdout.find("azure.client.default.key") == -1
